name: 690f
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.17
  - pip=25.2
  - python=3.9.23
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1

  # Mac-only packages removed for Windows
  # - libcxx
  # - ncurses
  # - readline

  - pip:
      - absl-py==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - dm-tree==0.1.8
      - dp-accounting==0.4.3
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.10.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.2.1
      - numpy==1.26.4
      - ollama==0.6.0
      - opacus==1.5.4
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==22.0
      - pandas==2.3.2
      - pillow==11.3.0
      - protobuf==6.32.1
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.1.0
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-estimator==2.15.0
      - tensorflow-privacy==0.9.0
      - tensorflow-probability==0.22.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - zipp==3.23.0
